### ISSUE TITLE
 Orphan datasets from Taiwan

### ISSUE THREAD

**Issue by kbraak** [gbif/watchdog#14]
Thanks to Mao-Ning Tuanmu for the analysis on the potential oprhans datasets from Taiwan. 

Here are the action points coming out of the analysis:

* http://www.gbif.org/dataset/51947020-98a2-11de-b4da-b8a03c50a862 should be deleted because it is a duplicate of http://www.gbif.org/dataset/29d56be4-2b76-4a05-887d-633a3c6a9a83 (**deletion todo in GBIF Registry**)
* http://www.gbif.org/dataset/79ae93e0-a2b8-11de-9f79-b8a03c50a862 endpoint changed to http://140.109.28.72/tapirlink/www/tapir.php/TFRI (**confirmed updated in GBIF Registry and re-crawl triggered manually**)
* http://www.gbif.org/dataset/8d7c4dd0-c75e-11dd-87ef-b8a03c50a862 endpoint changed to http://140.109.28.72/tapirlink/www/tapir.php/TAIF (**confirmed updated in GBIF Registry and re-crawl triggered manually**)
* http://www.gbif.org/dataset/98b2bb30-1627-11df-bd84-b8a03c50a862 should be deleted because it a duplicate of http://www.gbif.org/dataset/8d7c4dd0-c75e-11dd-87ef-b8a03c50a862 (**deletion pending in GBIF Registry - awaiting confirmation still**)
* http://www.gbif.org/dataset/c0e56940-1627-11df-bd84-b8a03c50a862 should be deleted because it a duplicate of http://www.gbif.org/dataset/79ae93e0-a2b8-11de-9f79-b8a03c50a862 (**deletion pending in GBIF Registry - awaiting confirmation still**)
* http://www.gbif.org/dataset/d2e12080-f1ca-11dd-b2d4-b8a03c50a862 should be deleted because it is a duplicate of http://www.gbif.org/dataset/29d56be4-2b76-4a05-887d-633a3c6a9a83 (**deletion todo in GBIF Registry**)
* @Maofangisme followed up directly with the publisher of http://www.gbif.org/dataset/88dc0756-f762-11e1-a439-00145eb45e9a No reply was received, therefore (**this has been identified as a true orphan requiring rescue**)

**Comment by kbraak** [comment]
Summary of actions taken:
* 51947020-98a2-11de-b4da-b8a03c50a862 has been deleted
* 79ae93e0-a2b8-11de-9f79-b8a03c50a862 confirmed to be crawling normally now
* 8d7c4dd0-c75e-11dd-87ef-b8a03c50a862 confirmed to be crawling normally now
* 98b2bb30-1627-11df-bd84-b8a03c50a862 has been deleted
* c0e56940-1627-11df-bd84-b8a03c50a862 has been deleted
* d2e12080-f1ca-11dd-b2d4-b8a03c50a862 has been deleted

Summary of actions remaining to do:
* 88dc0756-f762-11e1-a439-00145eb45e9a identified as a true orphan and scheduled for adoption

**Comment by MattBlissett** [comment]
88dc0756-f762-11e1-a439-00145eb45e9a rescued.
