### ISSUE TITLE
Orphan datasets from Colombia

### ISSUE THREAD

**Issue by kbraak** [gbif/watchdog#15]
Leonardo (NM - GBIF Colombia) has performed an analysis of Colombia's orphan datasets available [here](https://docs.google.com/spreadsheets/d/1LOYvb2WpLs9FQ_tGzwcCw9yZcbX1iGxl4QQHDextK_8/edit?usp=sharing). 

It appears all datasets in the [Colombia's list of potential orphans](https://github.com/kbraak/watchdog/blob/master/lists/orphans/Colombia.tsv) weren't being recrawled by GBIF because they had the wrong endpoint URL. This can happen when the IPT base URL is changed, but the URL change isn't propagated properly to the GBIF Registry - easily done by triggering an "Update Registration" from the "Edit GBIF Registration" page in the IPT.

**Comment by MattBlissett** [comment]
No orphans now from Colombia.

**Comment by jlegind** [comment]
All Colombian datasets in the file updated to "NO" orphaned status
