### ISSUE TITLE
Orphan datasets from Chile

### ISSUE THREAD

**Issue by kbraak** [gbif/watchdog#16]
Of the [6 orphan datasets from Chile](https://github.com/kbraak/watchdog/blob/master/lists/orphans/Chile.tsv), the only dataset that needs a confirmation that it can be rescued by the publisher is "Base de datos de colectas Región de Atacama en Herbario de la Universidad de La Serena". Francisco Moreno Herrera is leading the investigation into the status of these datasets.

**Comment by MattBlissett** [comment]
No orphans now from Chile.
