### ISSUE TITLE
Orphan datasets from Andorra

### ISSUE THREAD

**Issue by kbraak** [gbif/watchdog#27]
All 7 of Andorra's datasets are offline because the [CENMA IPT](https://www.gbif.org/installation/f13875b1-0b16-4171-977a-7af34c53eae7) is offline at http://www.ipt-cenma.ad 

The Node Manager has been alerted of the problem. These datasets are [scheduled for adoption in 2018](https://github.com/gbif/watchdog/wiki/AdoptionPlan#phase-2-2018) in case they cannot be brought back online soon.

**Comment by MattBlissett** [comment]
All back online since December.

**Comment by kcopas** [comment]
New Living Atlases site launched last week: https://www.gbif.ad
