### ISSUE TITLE
Orphan datasets from BDJ

### ISSUE THREAD

**Issue by kbraak** [gbif/watchdog#28]
52 out of 231 datasets are offline, all published via BDJ's custom publishing software. 

BDJ has been alerted of the problem. These datasets are [scheduled for adoption in 2018](https://github.com/gbif/watchdog/wiki/AdoptionPlan#phase-2-2018) (see under the Participant Node Managers Committee) in case they cannot be brought back online soon.

**Comment by kbraak** [comment]
Problem reported fixed by Teodor. We need to monitor results of next indexing round, and ensure these datasets don't get rescued in 2018/removed from the 2018 rescue list.

**Comment by timrobertson100** [comment]
In case it helps `curl -u kbraak:<your_password> -X POST https://api.gbif.org/v1/dataset/crawl/<uuid>` and they'll crawl now (has to be a REGISTRY_ADMIN account).

**Comment by MattBlissett** [comment]
This all came back online between November and January.
