### ISSUE TITLE
Orphan dataset from Serbia

### ISSUE THREAD

**Issue by kbraak** [gbif/watchdog#29]
The one and only dataset published by Serbia https://www.gbif.org/dataset/9060319d-ceb2-44ac-9423-efaa4a88214f if currently offline because the Biodiversity Serbia IPT is offline http://hoverf-biosense.rhcloud.com/archive.do?r=hfdata 

Both the IPT admin and dataset owner have been alerted of the problem. This dataset is [scheduled for adoption in 2018](https://github.com/gbif/watchdog/wiki/AdoptionPlan#phase-2-2018) (see under the Participant Node Managers Committee) in case it cannot be brought back online soon.

**Comment by MattBlissett** [comment]
Rescued.
