### ISSUE TITLE
Display the TITLE of the orphaned dataset

### ISSUE THREAD

**Issue by dagendresen** [gbif/watchdog#32]
It might be useful for a quick overview to display the TITLE of the orphaned datasets at https://orphans.gbif.org/ (and a direct link to the GBIF portal page for the respective dataset).

**Comment by MattBlissett** [comment]
Seems reasonable -- done.

Another way to find all orphan datasets is by searching for the appropriate machine tags: http://api.gbif.org/v1/dataset?machineTagNamespace=orphans.gbif.org&machineTagName=status&machineTagValue=RESCUED
